<table style="margin: 0px auto;background-color:rgba(0, 0, 0, 0);">
    <tr>
        <td><img src="https://upload.wikimedia.org/wikipedia/commons/3/3b/Udacity_logo.png" width=150 height=150 style="float;"></td>
        <td><p style="text-align:center;color:#5EA1DD;font-size:175%">Udacity Data Science Nanodegree - Student Notes &nbsp;&nbsp;<p></td>
    </tr>
</table>

<p style="text-align:center;color:#445089">Navneet Kumar ||
<a href="https://github.com/Navneetkr870">https://github.com/Navneetkr870</a> || <a href="https://www.linkedin.com/in/navneetkr870/">https://www.linkedin.com/in/navneetkr870/</a></p>

____________________________________________________________________________________________

<p style="text-align:left;">
    <a href=" "> Previous Page </a>
    <span style="float:right;">
        <a href=" "> Next Page </a>
    </span>
</p>

<p style="text-align:center;color:#2CB23C;font-size:200%;"> 
    -- 1.3 Python Basics - Numpy -- 
</p>

____________________________________________________________________________________________

In this section we would look into basics of Numpy

---

## 1. Introduction to NumPy - Numerical Python

NumPy stands for Numerical Python and it's a fundamental package for scientific computing in Python. NumPy provides Python with an extensive math library capable of performing numerical computations effectively and efficiently. These lessons are intended as a basic overview of NumPy and introduces some of its most important features.

## 2. Version of numpy

In [1]:
!conda list numpy

# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.16.2           py37h19fb1c0_0  
numpy-base                1.16.2           py37hc3f5095_0  
numpydoc                  0.8.0                    py37_0  


Although the udacity tutorial asks for installing 1.13 but let's continue as of now

## 3. Why use Numpy ? 

Numpy work majorly on multidimensional arrays functions. Numpy supports extremely quick functions and the following function would show the speed at which it conducts operations

In [1]:
import time 
import numpy as np

In [2]:
x=np.random.random(10000000)

In [3]:
print(x)
print(len(x))

[0.72050763 0.78791661 0.8401779  ... 0.35659853 0.44526619 0.67852873]
10000000


In [4]:
start = time.time()
print(sum(x)/len(x))
print(time.time()-start)

0.5000356252290209
1.3420765399932861


In [12]:
start=time.time()
print(np.mean(x))
print(time.time()-start)

0.4999754042155034
0.035601139068603516


The above example shows the speed at which multidimensional arrays of numpy help calculations

## 4. Creating NumPy ndarrays

+ Unlike Python lists, NumPy arrays should contain items with the data type

In [5]:
# We create a rank 1 ndarray that only contains integers
Y = np.array([10,20,30,44])

# We create a rank 2 ndarray that only contains integers
# Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

# We print Y
print()
print('Y = \n', Y)
print()

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)


Y = 
 [10 20 30 44]

Y has dimensions: (4,)
Y has a total of 4 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


### Defining the data type for the numpy

In [12]:
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

# We print x
print(x.shape)
print('x = ', x)
print()

# We print the dtype x
print('The elements in x are of type:', x.dtype)


(5,)
x =  [1 2 3 4 5]

The elements in x are of type: int64


## 5. Creating NumPy ndarrays of rank 2

In [14]:
# We create a 2 x 3 ndarray full of fives. 
X = np.full((2,3), 5) 

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[5 5 5]
 [5 5 5]]

X has dimensions: (2, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32


In [16]:
# We create a a rank 1 ndarray with sequential integers from 0 to 19 and
# reshape it to a 4 x 5 array 
Y = np.arange(20).reshape(4, 5)

# We print Y
print()
print('Y = \n', Y)
print()

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)


Y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Y has dimensions: (4, 5)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


## 6. Slicing ndarrays

As we mentioned earlier, in addition to being able to access individual elements one at a time, NumPy provides a way to access subsets of ndarrays. This is known as slicing. Slicing is performed by combining indices with the colon : symbol inside the square brackets. In general you will come across three types of slicing:

1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]

In [17]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
Z = X[1:4,2:5]

# We print Z
print('Z = \n', Z)

# We can select the same elements as above using method 2
W = X[1:,2:5]

# We print W
print()
print('W = \n', W)

# We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
Y = X[:3,2:5]

# We print Y
print()
print('Y = \n', Y)

# We select all the elements in the 3rd row
v = X[2,:]

# We print v
print()
print('v = ', v)

# We select all the elements in the 3rd column
q = X[:,2]

# We print q
print()
print('q = ', q)

# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:,2:3]

# We print R
print()
print('R = \n', R)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

W = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Y = 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]

v =  [10 11 12 13 14]

q =  [ 2  7 12 17]

R = 
 [[ 2]
 [ 7]
 [12]
 [17]]


## 7. Boolean Indexing, Set Operations, and Sorting

You can run any Boolean function on the ndarray and return the values.<br>
You can also use set functions to get union, intersections or setdifference. 

### Boolean Indexing

In [19]:
ndarray = np.arange(1,17).reshape(4,4)
print(ndarray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [20]:
print(ndarray[ndarray>10])

[11 12 13 14 15 16]


In [21]:
ndarray[ndarray<5]=1

In [22]:
print(ndarray)

[[ 1  1  1  1]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [23]:
ndarray[:2,:2]

array([[1, 1],
       [5, 6]])

### Set Operations

In [24]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])

# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)

# We use set operations to compare x and y:
print()
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))


x =  [1 2 3 4 5]

y =  [6 7 2 8 4]

The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]


### Sorting

Sorting can performed using method (to change the original ndarray) or can also just display the sorted numbers.

In [27]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,11,size=(10,))

# We print x
print()
print('Original x = ', x)

# We sort x and print the sorted array using sort as a function.
print()
print('Sorted x (out of place):', np.sort(x))

# When we sort out of place the original array remains intact. To see this we print x again
print()
print('x after sorting:', x)


Original x =  [ 4  6  2  7  6  3  3  9 10  2]

Sorted x (out of place): [ 2  2  3  3  4  6  6  7  9 10]

x after sorting: [ 4  6  2  7  6  3  3  9 10  2]


---

In the next section, we will look into Functions